// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/visiter/About.vue')['default']
    Archive: typeof import('./src/components/visiter/Archive.vue')['default']
    Blog: typeof import('./src/components/visiter/Blog.vue')['default']
    BlogManager: typeof import('./src/components/admin/BlogManager.vue')['default']
    BlogPage: typeof import('./src/components/fragment/BlogPage.vue')['default']
    Detail: typeof import('./src/components/visiter/Detail.vue')['default']
    DetailManager: typeof import('./src/components/admin/DetailManager.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Footer: typeof import('./src/components/fragment/Footer.vue')['default']
    Music: typeof import('./src/components/visiter/Music.vue')['default']
    MusicManager: typeof import('./src/components/admin/MusicManager.vue')['default']
    Navbar: typeof import('./src/components/fragment/Navbar.vue')['default']
    Resource: typeof import('./src/components/visiter/Resource.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/visiter/Search.vue')['default']
    Tag: typeof import('./src/components/visiter/Tag.vue')['default']
    TagManager: typeof import('./src/components/admin/TagManager.vue')['default']
    Type: typeof import('./src/components/visiter/Type.vue')['default']
    TypeManager: typeof import('./src/components/admin/TypeManager.vue')['default']
    UserLogin: typeof import('./src/components/user/UserLogin.vue')['default']
  }
}
